import type { Metadata } from 'next';
import Image from 'next/image';
import { ArrowRight, Compass, Layers3, ShieldCheck } from 'lucide-react';
import { FinalCta } from '@/components/final-cta';
import { SiteShell } from '@/components/site-shell';

export const metadata: Metadata = { title: 'About Ascend On-Site Wellness', description: 'Learn how Ascend brings a decade of wellness operating experience in Lake Mary into communities and facilities across Central Florida.', alternates: { canonical: '/about/' } };

export default function AboutPage() {
  return (
    <SiteShell pageId="C-ABOUT">
      <section className="subpage-hero about-hero"><div className="shell editorial-grid"><div><p className="eyebrow">About Ascend</p><h1>Operating experience, brought into your community.</h1></div><div className="editorial-copy"><p>Ascend On-Site Wellness exists to help communities and facilities deliver a professional, dependable wellness experience without requiring their internal team to build and manage every part of the operation.</p><a className="text-link" href="#our-approach">See our operating approach <ArrowRight aria-hidden="true" size={18} /></a></div></div></section>
      <section className="about-story section-pad"><div className="shell resident-grid"><div className="resident-image"><Image src="/about-coaching.jpg" alt="Ascend coach guiding a client through a dumbbell exercise" width={1800} height={1201} priority /></div><div className="about-story-copy"><p className="eyebrow">Why Ascend On-Site Wellness exists</p><h2>Wellness works best when the experience and the operation support each other.</h2><p>For the last decade, Ascend has refined its wellness operation in Lake Mary, Florida. Ascend On-Site Wellness brings that operating experience into client communities and facilities as an on-site amenity.</p><p>That does not mean duplicating one facility everywhere. It means applying practical operating discipline—program design, professional delivery, standards, coordination, communication, and ongoing attention—to the environment in front of us.</p></div></div></section>
      <section id="our-approach" className="values-section section-pad"><div className="shell"><div className="section-heading"><p className="eyebrow">What a professional program requires</p><h2>Thoughtful design. Dependable delivery. Clear responsibility.</h2></div><div className="responsibility-grid values-grid"><article className="responsibility-card"><Compass aria-hidden="true" /><h3>Context first</h3><p>We begin with the population, facility, existing program, demand, and goals—not a fixed menu.</p></article><article className="responsibility-card"><Layers3 aria-hidden="true" /><h3>Flexible scope</h3><p>We support the level of responsibility the organization wants to delegate, from focused programming to a broader operation.</p></article><article className="responsibility-card"><ShieldCheck aria-hidden="true" /><h3>Professional standards</h3><p>Authority is built through process, quality expectations, appropriate delivery, and operational specificity.</p></article></div></div></section>
      <section className="service-area section-pad"><div className="shell editorial-grid"><div><p className="eyebrow">Where we serve</p><h2>Central Florida, with room to grow thoughtfully.</h2></div><div className="editorial-copy"><p>Ascend On-Site Wellness currently serves Seminole, Orange, Volusia, Lake, and Osceola counties. We do not claim a national footprint; future expansion should follow actual delivery capability.</p><a className="text-link" href="/active-adult-55-plus-communities/">Explore Active Adult & 55+ <ArrowRight aria-hidden="true" size={18} /></a></div></div></section>
      <FinalCta pageId="C-ABOUT" heading="Bring a more professional wellness experience to your facility." copy="Start with a practical conversation about your environment, residents, current program, and goals." />
    </SiteShell>
  );
}
